### ISSUE TITLE
Node này chạy local vẫn được đúng không thầy?

### ISSUE THREAD

**Issue by xuantinfx** [nguyenkha/forest.network#1]
Em có đem project này về và setup chạy ở local nhưng bị văng lỗi ngay dòng setup thứ 2 ạ!
Hay có cần thay đổi gì không thầy?
Ảnh chụp màn hình lúc bị văng ạ
![image](https://user-images.githubusercontent.com/34159561/49578231-d84cb700-f97b-11e8-82f5-6a7d0dc08ee5.png)

**Comment by khaq** [comment]
Em đang chạy trên Linux hả? Nếu vậy thêm lệnh
```
chown -R 100:1000 ./tendermint
```

**Comment by xuantinfx** [comment]
Dạ chạy trên Windows Container của Linux ạ.
Em thêm vào nó vẫn bị lỗi tương tự luôn thầy
![image](https://user-images.githubusercontent.com/34159561/49580348-4e9fe800-f981-11e8-87e8-b47585a52e74.png)
# Các bước em thực hiện
## `init tendermint và` `chown -R 100:1000 ./tendermint`
![image](https://user-images.githubusercontent.com/34159561/49580458-89a21b80-f981-11e8-9b6a-94217e3ec57d.png)
## `docker-compose up`
![image](https://user-images.githubusercontent.com/34159561/49580536-bc4c1400-f981-11e8-8c64-a1dc941773ff.png)
![image](https://user-images.githubusercontent.com/34159561/49580551-c40bb880-f981-11e8-862f-75543924c7a6.png)
![image](https://user-images.githubusercontent.com/34159561/49580568-cc63f380-f981-11e8-9f3a-d86347ca31a8.png)
![image](https://user-images.githubusercontent.com/34159561/49580578-d4bc2e80-f981-11e8-92f7-159cd6ad0821.png)
![image](https://user-images.githubusercontent.com/34159561/49580589-dbe33c80-f981-11e8-96a8-f77cba025d49.png)
![image](https://user-images.githubusercontent.com/34159561/49580601-e7cefe80-f981-11e8-88a8-50af11ec0d6d.png)
![image](https://user-images.githubusercontent.com/34159561/49580619-f0bfd000-f981-11e8-9c53-777d9ef19613.png)

**Comment by xuantinfx** [comment]
dạ vẫn không được, em chạy thử bằng cloud của google cũng không được luôn ạ
:(

**Comment by pqnguyen** [comment]
<img width="1440" alt="screen shot 2018-12-06 at 10 04 10 pm" src="https://user-images.githubusercontent.com/23742014/49592135-ebbf4880-f9a2-11e8-9a10-2b5894308da5.png">

Thầy ơi em chạy Testnet không đc :)

**Comment by nguyenkha** [comment]
> dạ vẫn không được, em chạy thử bằng cloud của google cũng không được luôn ạ
> :(

Post lại kết quả trên gg cloud.



> <img alt="screen shot 2018-12-06 at 10 04 10 pm" width="1440" src="https://user-images.githubusercontent.com/23742014/49592135-ebbf4880-f9a2-11e8-9a10-2b5894308da5.png">
> 
> Thầy ơi em chạy Testnet không đc :)
> 
> Em chỉ chạy được một trong hai Mainet hoặc testnet. Chứ không đc cả hai ?

Nếu muốn chạy cả 2 phải sửa `docker-compose` để không mapping trùng port.

**Comment by xuantinfx** [comment]
> > dạ vẫn không được, em chạy thử bằng cloud của google cũng không được luôn ạ
> > :(
> 
> Post lại kết quả trên gg cloud.
> 

Dạ thầy
Đây ạ
![image](https://user-images.githubusercontent.com/34159561/49638637-57ed8b00-fa3b-11e8-9fcd-e1b653f92823.png)

**Comment by nguyenkha** [comment]
> > > dạ vẫn không được, em chạy thử bằng cloud của google cũng không được luôn ạ
> > > :(
> > 
> > 
> > Post lại kết quả trên gg cloud.
> 
> Dạ thầy
> Đây ạ
> ![image](https://user-images.githubusercontent.com/34159561/49638637-57ed8b00-fa3b-11e8-9fcd-e1b653f92823.png)

`chown -R 100:1000 ./tendermint` chưa em...

**Comment by kennySix** [comment]
> Thiệt là chưa thử trên windows, nhưng thử `docker-compose down` rồi xóa thư mục`tendermint/data` rồi thử lại xem.

em bị lỗi giống bạn , có thử cách trên nhưng cũng không được luôn thầy

**Comment by nguyenkha** [comment]
> > Thiệt là chưa thử trên windows, nhưng thử `docker-compose down` rồi xóa thư mục`tendermint/data` rồi thử lại xem.
> 
> em bị lỗi giống bạn , có thử cách trên nhưng cũng không được luôn thầy

Huhu thầy không có máy windows để test, có ai teamview không?

**Comment by xuantinfx** [comment]
> > > Thiệt là chưa thử trên windows, nhưng thử `docker-compose down` rồi xóa thư mục`tendermint/data` rồi thử lại xem.
> > 
> > 
> > em bị lỗi giống bạn , có thử cách trên nhưng cũng không được luôn thầy
> 
> Huhu thầy không có máy windows để test, có ai teamview không?

Dạ mai em ở nhà cả ngày, nếu cần thì thầy có thể gọi em, em suport thiết bị tận tình ạ. Sđt của em là 037.308.1312

**Comment by xuantinfx** [comment]
Đêm nay cũng đc luôn ạ

**Comment by vominhtrius** [comment]
em cũng bị lỗi này trên windows và ubuntu thầy ạ @khaq

**Comment by nguyenkha** [comment]
> em cũng bị lỗi này trên windows và ubuntu thầy ạ @khaq

Windows thì tạm thời thầy chưa sửa được. Ubuntu thì add telegram thầy `@nguyenkha` rồi xem cho.

**Comment by nqtinh** [comment]
![image](https://user-images.githubusercontent.com/37231358/49692671-d741a280-fb92-11e8-9438-a3f8bfcaef9f.png)

Em pull bài mới của thầy về chạy thì bị lỗi này ạ.

**Comment by nguyenkha** [comment]
> ![image](https://user-images.githubusercontent.com/37231358/49692671-d741a280-fb92-11e8-9438-a3f8bfcaef9f.png)
> 
> Em pull bài mới của thầy về chạy thì bị lỗi này ạ.

Telegram...

**Comment by kennySix** [comment]
Về lỗi ERROR: for tendermint  Cannot create container for service tendermint: invalid volume specification: 'f59af934b5a1cc90f2cccaac16655f6cdfb6be766f64fd8672bf3db1b8b3e02e:[:rw': invalid mount config for type "volume": invalid mount path: '[' mount path must be absolute
ERROR: Encountered errors while bringing up the project.

Chạy docker ps để xem container hiện có -> docker stop + id để dừng container -> docker rm +id để xóa
-> chạy docker-compose down -> docker-compose run --rm tendermint init -> docker-compose up

![1](https://user-images.githubusercontent.com/45568241/49694420-657e4e80-fbbc-11e8-88d1-94b70a1f5043.PNG)
![2](https://user-images.githubusercontent.com/45568241/49694421-6616e500-fbbc-11e8-9970-293995a922da.PNG)
![3](https://user-images.githubusercontent.com/45568241/49694422-6616e500-fbbc-11e8-8a46-247d9369b5b9.PNG)
![4](https://user-images.githubusercontent.com/45568241/49694423-6616e500-fbbc-11e8-993e-700bc93863d8.PNG)

**Comment by progamerxh** [comment]
Có ai sửa được cái lỗi chạy trên window chưa

**Comment by progamerxh** [comment]
> > Có ai sửa được cái lỗi chạy trên window chưa
> 
> @xuantinfx @nqtinh

À em pull code mới của thầy thì chạy được rồi
