### ISSUE TITLE
Tài khoản đầu tiên trong blockchain?

### ISSUE THREAD

**Issue by kan97** [nguyenkha/forest.network#11]
Tài khoản có số tiền bằng hằng số Number.MAX_SAFE_INTEGER của JavaScript.
Tài khoản đó ở đâu ra vậy thầy?
Em có cần lưu tài khoản đó vào database không?

**Comment by nguyenhuedang** [comment]
Lúc tạo ra block đầu tiên [genesis block](https://en.bitcoin.it/wiki/Genesis_block) mình sẽ định nghĩa xem tiền sẽ được chuyển cho tài khoản nào, và tài khoản đó nằm trong chỗ này: https://github.com/nguyenkha/forest.network/blob/master/docker-compose.yaml#L12
