### ISSUE TITLE
Value của key 'followings' trong update_account operation

### ISSUE THREAD

**Issue by ttnhon** [nguyenkha/forest.network#13]
const Followings = vstruct([
  { name: 'addresses', type: vstruct.VarArray(vstruct.UInt16BE, vstruct.Buffer(35)) },
]);
addresses là danh sách những tài khoản follow mới hay là toàn bộ danh sách following của mình (tức là nối thêm pubkey mới vào mảng following hiện có) vậy thầy?

**Comment by nguyenkha** [comment]
Nối thêm vào, `followings` là toàn bộ cả mới lẫn cũ.
