### ISSUE TITLE
Lỗi Post params

### ISSUE THREAD

**Issue by phuvinh2211** [nguyenkha/forest.network#14]
Em đã thử rất nhiều cách chuyển đổi sang buffer nhưng vẫn bị lỗi như vầy ạ ! 
![image](https://user-images.githubusercontent.com/35805931/50359589-dc89ee80-058f-11e9-8ff0-c63c1f74c69a.png)

**Comment by nguyenkha** [comment]
Phải encode content trước bằng `PlainTextContent` thành `Buffer` rồi đặt vào `content`

**Comment by phuvinh2211** [comment]
Dạ cám ơn thầy em làm được rồi !
