### ISSUE TITLE
Lỗi decode PlaintTextCotent

### ISSUE THREAD

**Issue by vominhtrius** [nguyenkha/forest.network#16]
- Tại block 17193 và một số khác, có transaction Post, sau khi  decode Transaction, thì em tiến hành decode  params.content thì báo lỗi **RangeError: not engouh data for decode**. Nhưng trên explorer của thầy vẫn báo là transactiond đó succes.
- Một số transaction post khác, vẫn decode được và đầy đủ nội dung của bài post.
- Đây là hình báo lỗi: ![Decode-Error](https://i.imgur.com/V0ANcw2.png)
- Đây là struct e dùng để decode content
```nodejs
const PlainTextContent = vstruct([
    { name: 'type', type: vstruct.UInt8 },
    { name: 'text', type: vstruct.VarString(vstruct.UInt16BE) },
]);
```

**Comment by vominhtrius** [comment]
- Em có check lại code của thầy thì, thầy chỉ log transaction đó ra, mà không tiến hành decode, kiểm tra. Nên điều này dẩn đến việc kiểm tra transaction succes của thầy và em khác nhau -> Sequence khác nhau.

**Comment by progamerxh** [comment]
Sequence thì lấy sequence của tx gán vô, trong node đã có sẵn bước verify rồi, cần gì check thêm

**Comment by vominhtrius** [comment]
> Sequence thì lấy sequence của tx gán vô, trong node đã có sẵn bước verify rồi, cần gì check thêm

vấn đề là không decode được nội dung của bài post? Không biết bạn có thử get bài Post đó từ server của bạn chưa ?

**Comment by progamerxh** [comment]
Get rồi, đẻ ở dạng nhị phân, khi nào client cần thì lấy ra đọc, lỗi thì ignore nó

**Comment by vominhtrius** [comment]
> Get rồi, đẻ ở dạng nhị phân, khi nào client cần thì lấy ra đọc, lỗi thì ignore nó

👍 :))

**Comment by progamerxh** [comment]
Dùng cả csr và ssr để giảm tải server

**Comment by nguyenkha** [comment]
Việc node decode nội dung post trong tx là không cần thiết, vì trong thiết kế người dùng có thể mã hóa thông tin (mình sẽ cung cấp spec) nên việc giải mã nội dung post không thành công không có nghĩa là transaction thất bại, hệ thống chấp nhận bất kể người dùng post lên nội dung gì. Trường hợp đã thử hết tất cả các type post mà không thành công thì coi như nội dung đã được mã hóa (hoặc ở định dạng chưa có spec) không cần xử lý nội dung. Đó là lý do trên explorer mình vẫn hiển thị post đó nhưng dưới dạng không giải mã được (post ... bytes)

**Comment by vominhtrius** [comment]
Tks thầy, e handle được rồi.
