### ISSUE TITLE
Lỗi Followed

### ISSUE THREAD

**Issue by phuvinh2211** [nguyenkha/forest.network#17]
![image](https://user-images.githubusercontent.com/35805931/50373240-3b8e4880-060e-11e9-826b-c4fb51180105.png)

![image](https://user-images.githubusercontent.com/35805931/50373328-04209b80-0610-11e9-9282-0c2f39d84136.png)

Hiện tại em đang bị sai cấu trúc của Follows em có thử encode hàm following nhưng không được ạ ?

**Comment by nguyenkha** [comment]
Tương tự như post, em phải dùng struct `Followings` để encode...

**Comment by phuvinh2211** [comment]
addresses em truyền vào như vậy đúng chưa thầy ?

**Comment by nguyenkha** [comment]
Làm tương tự post đó, lỗi y chang mà em (https://github.com/nguyenkha/forest.network/issues/14). Dùng `Followings` encode thành `Buffer` rồi để buffer vào value của update account.

**Comment by progamerxh** [comment]
Bổ sung nhé, xem lại chỗ lib/tx để coi cái base32.decode(address) không phải truyền mảng ở dạng đọc được như trên đâu
