### ISSUE TITLE
Không thể thực hiện POST sử dụng JSONRPC

### ISSUE THREAD

**Issue by nghianv100** [nguyenkha/forest.network#18]
Em chào thầy, Em không thể thực hiện POST Request sử dụng JSONRPC, giá trị params là base64 của Transaction đã encode.  Khi gửi request thì response body không trả về gì cả.
![screenshot_20181222_181910](https://user-images.githubusercontent.com/38467709/50373808-94fa7580-0616-11e9-9991-0ec7b13cbeaf.png)

**Comment by nguyenkha** [comment]
Bạn để nội dung phần request dạng code lên trên đây... chứ để trong hình thì sao kiểm tra được?

**Comment by nghianv100** [comment]
Cái đó em thử gửi request trên postman nhưng cũng không được đó thầy. Code của em đây ạ:

````javascrip
let { encode, decode, verify, sign, hash } = require('../lib/tx');
let axios = require('axios');

let tx = {
    version: 1,
    sequence: 28,
    memo: Buffer.alloc(0),
    operation: 'payment',
    params: {
        address: 'GBWUF2JNJ7WGBREPBIFQIJFTQM3BLX65OD5CGDJWI3AH3JBGNFHTNM4O',
        amount: 10
    }
}

sign(tx, 'secret_key');

let dataEncoded = encode(tx).toString('base64');

axios.post('https://komodo.forest.network/', {
    "jsonrpc": "2.0",
    "id": "",
    "method": "broadcast_tx_commit",
    "params": [`${dataEncoded}`]
})
    .then(res => console.log(res.data))
    .catch(err => console.log(err));
````

Kết quả in ra là rỗng ạ. Em đã kiểm tra đúng sequence và secrect key.

**Comment by nguyenkha** [comment]
Ý mình là nội dung base64 kìa... bạn có thể ghi ra để coi thử không?

**Comment by nghianv100** [comment]
Dạ đây thầy:
````
ATAefdmXvmI4E36EE2yV/TyTsHWGuyatyDPCSIPVKhZPczIVAAAAAAAAABwAAgArMG1C6S1P7GDEjwoLBCSzgzYV391w+iMNNkbAfaQmaU82s44AAAAAAAAACgl9rmYoOqBY2hpFDUwaof/Wza9j71dDKzMQH5/RfcZZsoucgrJyHDuAiq2MQ+I3u4uxtnOkfrql66n6pTGxUQE=
````

**Comment by nguyenkha** [comment]
Mình vừa thử và broadcast thành công mà bạn:

[https://forest.network/transactions/117A23DC1AD80618FEBD35C3D04609757B9061A7BDCD70F995BD35B07F4F7D53](https://forest.network/transactions/117A23DC1AD80618FEBD35C3D04609757B9061A7BDCD70F995BD35B07F4F7D53)

```
curl -X POST https://komodo.forest.network/ -d '{ "jsonrpc": "2.0", "id": 5, "method": "broadcast_tx_commit", "params": ["ATAefdmXvmI4E36EE2yV/TyTsHWGuyatyDPCSIPVKhZPczIVAAAAAAAAABwAAgArMG1C6S1P7GDEjwoLBCSzgzYV391w+iMNNkbAfaQmaU82s44AAAAAAAAACgl9rmYoOqBY2hpFDUwaof/Wza9j71dDKzMQH5/RfcZZsoucgrJyHDuAiq2MQ+I3u4uxtnOkfrql66n6pTGxUQE="] }'
```

**Comment by nghianv100** [comment]
Để em POST nó dưới dạng chuỗi JSON thử, em cảm ơn thầy

**Comment by nguyenkha** [comment]
Phần code của bạn thì đoạn thiếu dấu `"`
```
"params": [`"${dataEncoded}"`]
```

**Comment by nghianv100** [comment]
Cũng không được luôn thầy ạ :(

**Comment by nguyenkha** [comment]
Mình broadcast (transaction của bạn) được bằng curl nghĩa là code của bạn có sai chỗ nào đó (header, content type...). Mặt khác các bạn khác vẫn broadcast được thì chắc chắn lỗi không ở server và tx encoder. Xem lại document của axios hoặc thử thư viện khác.

**Comment by nghianv100** [comment]
Dạ, để em thử các header khác của thằng axios

**Comment by nguyenkha** [comment]
Sửa lại `id=1` hay số nào cũng được đi em.

**Comment by nghianv100** [comment]
Dạ, được rồi thầy =))
