### ISSUE TITLE
Height là gì vậy thầy?

### ISSUE THREAD

**Issue by xuantinfx** [nguyenkha/forest.network#2]
# Như hôm bữa thầy có nói mỗi ngày có 86400 block được tạo ra, em có một số thắc mắc ạ
## 2. Height là thể hiện của cái gì trong hệ thống ạ, nếu là block cuối cùng cũng không phải?

**Comment by nguyenkha** [comment]
1. Mình đã chỉnh sửa để không tạo block trống nữa, có transaction mới tạo.

2. Height là vị trí của block thôi, height = 1 => block số 1, latest height mới là block cuối cùng.

**Comment by xuantinfx** [comment]
Dạ em cám ơn thầy
