### ISSUE TITLE
Lỗi buffer instance khi sign tx ở front-end

### ISSUE THREAD

**Issue by tolu5455** [nguyenkha/forest.network#20]
Em chào thầy, khi em ký một transaction ở front-end sử dụng hàm sign của thầy thì nó luôn báo lỗi value must be a Buffer instance
![image](https://user-images.githubusercontent.com/25074727/50380588-22cd7380-069e-11e9-94bf-5e0647c66f25.png)

**Comment by nguyenkha** [comment]
Em check coi đang xài code encode decode version nào vậy?

**Comment by nguyenkha** [comment]
https://github.com/nguyenkha/forest.network/issues/8

**Comment by tolu5455** [comment]
Dạ em mới cập nhật lại rồi import vô nhưng vẫn bị thầy

**Comment by nguyenkha** [comment]
Vậy sao các bạn khác không bị? Mình thử dùng webpack và encode/decode/sign đều bình thường cả?

**Comment by tolu5455** [comment]
Cũng hàm đó nhưng em để bên backend thì kí bình thường thầy. Nhưng đem qua frontend thì bị lỗi như vậy.

**Comment by nguyenkha** [comment]
Ý mình nói là front end chứ không phải back end bạn. Mình vừa expose forest.network api trên explorer (nhớ F5), bạn có thể gõ thử vào console trên Chrome để check.

```js
var transaction = { version: 1, memo: forestNetwork.Buffer.alloc(0), sequence: 1, operation: 'payment', params: { address: 'GB73OPHUZC3RSDEU2LYV5T7MEAN2Q26HYQPDYIENGNBUHW5CXAQ6UJOO', amount: 1 }};
forestNetwork.tx.sign(transaction, 'SAKX6XYIQKWNNYIZUK33PYM7YJAPURMEQVM4LM6YOG42KPPZFB5GV424');
forestNetwork.tx.encode(transaction).toString('hex');
```

Lưu ý, `forestNetwork.Buffer` được dùng do trình duyệt không có sẵn `Buffer`. Nếu dùng webpack thì chỉ cần dùng `Buffer` như trong nodejs.

**Comment by hungphat11997** [comment]
Dạ em cũng gặp lỗi này. Phần foresnetwork API này có phải install vào project không ạ. Em cảm ơn thầy.

**Comment by nguyenkha** [comment]
@hungphat11997 Mình đã trả lời ở trên, code vẫn chạy trên front end một cách bình thường, bên bạn phải xem lại đã cấu hình project đúng chưa (buffer cho trình duyệt). Cái forest network api trên explorer chính là `lib/tx` của repo này thôi. Đây là một phần code của explorer (chạy ngay trong trình duyệt).

```js
import tx from 'forest.network/lib/tx';

// Global tx
global.forestNetwork = { tx, Buffer };
```

**Comment by hungphat11997** [comment]
Dạ em cảm ơn thầy!

**Comment by tolu5455** [comment]
Em cấu hình lại đc rồi thầy. Em cám ơn thầy
