### ISSUE TITLE
Lỗi thư viện base32.js khi chạy trên trình duyệt.

### ISSUE THREAD

**Issue by nghianv100** [nguyenkha/forest.network#21]
````javascript
const Followings = vstruct([
        { name: 'addresses', type: vstruct.VarArray(vstruct.UInt16BE, vstruct.Buffer(35)) },
    ]);

    Followings.encode({
        addresses: [base32.decode('GAPH3WMXXZRDQE36QQJWZFP5HSJ3A5MGXMTK3SBTYJEIHVJKCZHXGMQV'), base32.decode('GAO4J5RXQHUVVONBDQZSRTBC42E3EIK66WZA5ZSGKMFCS6UNYMZSIDBI')]
    });
````

Em chào thầy, cùng 1 đoạn code ở trên nhưng khi chạy ở Front-end thì báo lỗi `value must be a Buffer instance`, còn chạy ở Node thì bình thường.
Ở front và node em import lần lượt như sau:

````
import base32 from 'base32.js';
````

````
let base32 = require('base32.js');
````

Thầy kiểm tra giúp em với ạ.

**Comment by khaq** [comment]
Em convert kết quả decode address thành `Buffer` rồi mới đưa vào. Tương tự: https://github.com/nguyenkha/forest.network/blob/master/lib/tx/v1.js#L56

**Comment by nghianv100** [comment]
Dạ được rồi thầy ^^
