### ISSUE TITLE
Lấy danh sách follower

### ISSUE THREAD

**Issue by thinhnhq** [nguyenkha/forest.network#22]
Thầy ơi cho em hỏi làm light app thì em lấy danh sách follower như thế nào ạ.
Danh sách following em thì em lấy được bằng cách duyệt toàn bộ transaction, lấy transaction có  operation là update_account và có key là  followings mới nhất. Còn cái list follower em không biết lấy như thế nào.

**Comment by khaq** [comment]
Follower không thể lấy với light app em.

**Comment by thinhnhq** [comment]
vậy light app ko cần lấy follower hả thầy?

**Comment by khaq** [comment]
Cái đó đâu có trong yêu cầu?

**Comment by progamerxh** [comment]
thầy chỉ kêu làm danh sách theo dõi (following) thôi mà :v

**Comment by thinhnhq** [comment]
dạ em cảm ơn thầy :)
