### ISSUE TITLE
Không gửi hash Giao dịch vào broad_cast đc ! 

### ISSUE THREAD

**Issue by vippergod123** [nguyenkha/forest.network#3]
Em có tạo và hash giao dịch như trong hình, sau đó gửi lên broad cast nhưng nó lại trả về như hình thứ 2, em có query search tx theo hash vừa làm nhưng lại ra Unsupport version ạ ! Không biết em có làm thiếu chỗ nào không thầy ? 

https://drive.google.com/drive/folders/1cm80hvlPHkqenYQ30BRVyw7IdBlYX2Of?usp=sharing[](url)

**Comment by nguyenkha** [comment]
Gửi transaction được encode chứ sao lại gửi hash...
