### ISSUE TITLE
Problem when start project

### ISSUE THREAD

**Issue by duongconghaicong** [nguyenkha/forest.network#4]
Thầy và mọi người giải thích dùm, khi em start project thì báo lỗi sau:
![capture](https://user-images.githubusercontent.com/33664509/49699928-224acc80-fc0a-11e8-8fbe-2f0a04d99520.PNG)
Mong mọi người giải thích. Thanks all

**Comment by xuantinfx** [comment]
start sai cách rồi bạn
Bạn tìm hiểu Docker để start cho nhanh
Theo mình thấy để start 1 cách bình thường thì phải setup môi trường rất nhiều, rất mất thời gian

**Comment by duongconghaicong** [comment]
@xuantinfx  cho mình xin thông tin về lỗi này được không bạn, chạy lệnh docker-compose up :
![capture](https://user-images.githubusercontent.com/33664509/49707814-9a8fad00-fc5f-11e8-8029-126d5d937f9f.PNG)
![capture1](https://user-images.githubusercontent.com/33664509/49707815-9a8fad00-fc5f-11e8-9731-6de72fb68adb.PNG)
![capture2](https://user-images.githubusercontent.com/33664509/49707817-9b284380-fc5f-11e8-9b45-56990e7710ac.PNG)
thanks bạn

**Comment by xuantinfx** [comment]
Hình như bạn chạy thiếu lệnh Init rồi thì phải

**Comment by duongconghaicong** [comment]
Mình có chạy ở trên rồi bạn

**Comment by nguyenkha** [comment]
```
docker-compose down
```
rồi chạy lại lần nữa, có vấn đề gì đó mà app không truy cập được db
P.S: Code cũ rồi, pull code mới trước

**Comment by DamVanHuan** [comment]
thầy @nguyenkha  ơi e init tendermint bị lỗi này ạ
![image](https://user-images.githubusercontent.com/33088398/49778027-b36a9200-fd35-11e8-86e9-44d344da0e54.png)

**Comment by nguyenkha** [comment]
> thầy @nguyenkha ơi e init tendermint bị lỗi này ạ
> ![image](https://user-images.githubusercontent.com/33088398/49778027-b36a9200-fd35-11e8-86e9-44d344da0e54.png)

Start lại docker với quyền admin

**Comment by DamVanHuan** [comment]
> > thầy @nguyenkha ơi e init tendermint bị lỗi này ạ
> > ![image](https://user-images.githubusercontent.com/33088398/49778027-b36a9200-fd35-11e8-86e9-44d344da0e54.png)
> 
> Start lại docker với quyền admin

đã start với quyền admin mà vẫn v á thầy

**Comment by nguyenkha** [comment]
Start docker for windows với quyền admin,m chứ không phải start cái shell với quyền admin.

**Comment by DamVanHuan** [comment]
> Start docker for windows với quyền admin chứ không phải start cái shell với quyền admin. Bạn nên google lỗi trước khi hỏi tiếp!

e đã start docker chứ k phải shell đâu thầy, lỗi này e tìm thì bảo dùng compose down rồi compose up mà vẫn bị vậy

**Comment by DamVanHuan** [comment]
> áy của b

em cảm ơn thầy ^^
