### ISSUE TITLE
Tính số dư tài khoản ? 

### ISSUE THREAD

**Issue by vippergod123** [nguyenkha/forest.network#5]
Thầy ơi ! Server của nhóm tự tính số dư tài khoản theo block đọc đc từ public key fai k thầy ? hay là server của thầy có hỗ trợ tính số dư ạ ? (Số dư tài khoản sau khi chuyển tiền giao dịch)

**Comment by nguyenkha** [comment]
Bạn phải tính dựa vào toàn bộ các transaction đã có của account.

**Comment by vippergod123** [comment]
à thầy ơi ! Cho em hỏi ngu 1 câu. chạy docker để làm gì v thầy ? em đã đọc đc transaction, payment và create account hết r nhưng không dùng gì tới docker ạ ?

**Comment by nguyenkha** [comment]
Google đi em...

**Comment by hung211097** [comment]
Thầy cho em hỏi cái "t" trong công thức tính Năng lượng đã sử dụng trong chu kỳ biến đổi là gì và đơn vị của nó ạ?

**Comment by hung211097** [comment]
Cho em hỏi cái txSize trong code của Thầy là từ req.tx.length, tx là chuỗi data trong block chưa được decode phải ko Thầy? Tại em lấy length của nó tính thử ko ra giống với Thầy, public key của em: GBIDPG4BFSTJSR3TYPJG4S4R2MEZX6U6FK5YJVIGD4ZJ3LTM4B5IS4RB, em tạo transactions ở block 3645, chuỗi tx trước khi decode của em 236 bytes, nhưng em thấy trên forest.network của Thầy là 175 bytes ạ

**Comment by nguyenkha** [comment]
> 3645

Ý bạn là: https://komodo.forest.network/tx?hash=0x1FFFE4250E43F62405FF0A05CB91F7E6E7FF53088F7370697298C7ECCE88A904

236 là số ký tự trong chuỗi base64, bạn chuyển về dạng Buffer/ByteArray/Uint8Array sẽ thấy có 175 bytes thôi
```
Buffer.from(..., 'base64')
```

**Comment by nguyenkha** [comment]
> Thầy cho em hỏi tính toán năng lượng lại khi thực hiện transactions được không ạ? Em thấy trên forest network của thầy năng lượng được cập nhật lại theo thời gian luôn mà em làm như vậy query update hết năng lượng các users sẽ khá tốn thời gian và việc truy cập, chỉnh sửa database khá nhiều ạ

Em chỉ cần tính năng lượng đến transaction cuối cùng của account đó thôi. Khi cần hiển thị thì tính tiếp tới thời điểm hiện tại. Cái thầy tính trên web chỉ là năng lượng ước tính tới thời điểm hiện tại thôi.
