### ISSUE TITLE
Create Transaction

### ISSUE THREAD

**Issue by DuongTheChung** [nguyenkha/forest.network#6]
Thầy cho em hỏi lúc em tạo thử transaction để test hiện lỗi này là gì vậy ạ: 
![12](https://user-images.githubusercontent.com/18650688/49871512-097c2a00-fe49-11e8-8b21-f050f525243c.png)

**Comment by progamerxh** [comment]
Operation là số

**Comment by progamerxh** [comment]
Thiếu amount trong params

**Comment by DuongTheChung** [comment]
ok để mình thử xem tks bạn

**Comment by DuongTheChung** [comment]
bạn ơi làm sao mà đưa cái transaction này lên cái node được nhỉ

**Comment by progamerxh** [comment]
> bạn ơi làm sao mà đưa cái transaction này lên cái node được nhỉ

Chiều cúp học đúng không
![image](https://user-images.githubusercontent.com/20384723/49873622-ebb1c380-fe4e-11e8-9e48-913a68f02a81.png)
Commit qua cái api này
https://komodo.forest.network/broadcast_tx_commit?tx=

**Comment by DuongTheChung** [comment]
chiều mình đi học mà ngồi xa quá không  thấy gì hết bạn có cái ảnh (hay cái đoạn code hồi chiều của thầy huy cho mình xin với)

**Comment by progamerxh** [comment]
> chiều mình đi học mà ngồi xa quá không thấy gì hết bạn có cái ảnh (hay cái đoạn code hồi chiều của thầy huy cho mình xin với)

Ở trên còn thiếu cái .toString('hex') thôi mà, thêm cái 0x vào trước đoạn hex rồi dán vào cuối cái link này thôi https://komodo.forest.network/broadcast_tx_commit?tx=
![48156178_282883735748829_4865908744745123840_n](https://user-images.githubusercontent.com/20384723/49874029-f6b92380-fe4f-11e8-9700-21cf911c0f14.jpg)

**Comment by DuongTheChung** [comment]
bạn ơi mình chạy bằng thư viện tendermint mà nó ra lỗi này bạn có biết là lỗi gì không 
![123](https://user-images.githubusercontent.com/18650688/49875264-287fb980-fe53-11e8-9e77-227f949bf935.png)
---------------------------------------
Lỗi
![1234](https://user-images.githubusercontent.com/18650688/49875296-3c2b2000-fe53-11e8-851b-9fac5c87db5a.png)

**Comment by progamerxh** [comment]
> ## bạn ơi mình chạy bằng thư viện tendermint mà nó ra lỗi này bạn có biết là lỗi gì không
> ![123](https://user-images.githubusercontent.com/18650688/49875264-287fb980-fe53-11e8-9e77-227f949bf935.png)
> Lỗi
> ![1234](https://user-images.githubusercontent.com/18650688/49875296-3c2b2000-fe53-11e8-851b-9fac5c87db5a.png)

Đã bảo là thêm 0x đằng trước cái hex -_-
![image](https://user-images.githubusercontent.com/20384723/49875438-988e3f80-fe53-11e8-9ce3-01a1a94ff0fe.png)

**Comment by DuongTheChung** [comment]
ok được rồi tại mình xài cái thư việc kia ,chứ không đưa trực tiếp lên link nên lỗi,Tks bạn nhiều nha

**Comment by DuongTheChung** [comment]
> Thầy cho em hỏi lúc em tạo thử transaction để test hiện lỗi này là gì vậy ạ:
> ![12](https://user-images.githubusercontent.com/18650688/49871512-097c2a00-fe49-11e8-8b21-f050f525243c.png)
