### ISSUE TITLE
Lỗi "Sequence mismatch"

### ISSUE THREAD

**Issue by lvduong1** [nguyenkha/forest.network#7]
Nhờ thầy và các bạn xem giúp mình. Mình tạo 1 transaction. Sau khi post lên thì bị lỗi này . sequence trước khi thực hiện giao dịch của sender là 153
![image](https://user-images.githubusercontent.com/45383366/49910300-bb9d0b80-feb4-11e8-93e6-30a1041d9619.png).
Chi tiết giao dịch
![image](https://user-images.githubusercontent.com/45383366/49910852-d8d2d980-feb6-11e8-8bb7-4668e3152af4.png)

**Comment by nguyenkha** [comment]
Account này sequence đang là 0 (chưa thực hiện giao dịch nào)? https://forest.network/accounts/GDDEPQGEOP7UPCZX3VPNVJCJS4HSLPLBQTSAKWK2TG463YCFEYW6QBQU
