### ISSUE TITLE
Sign một transaction 

### ISSUE THREAD

**Issue by N1H4Q0T2** [nguyenkha/forest.network#8]
Thầy ơi cho em hỏi là mình sign 1 transaction trên frontend được không thầy (tại em không có làm phần BE). Em không thể sign trên frontend. Nó toàn báo lỗi "value must be Buffer instance" (https://prnt.sc/luepa3)
Code em sign 1 transaction (http://prntscr.com/lueqg9)

**Comment by N1H4Q0T2** [comment]
![image](https://user-images.githubusercontent.com/45492918/49938164-a0111f80-ff0b-11e8-8d5e-5b820973b164.png)

**Comment by nguyenkha** [comment]
Rồi, update lại module `forest.network` và import `lib/tx` thay cho `lib/transaction`

**Comment by N1H4Q0T2** [comment]
Em sign được rồi thầy. Nãy thầy update code mới mà em ko để ý

**Comment by nguyenkha** [comment]
Bạn chép file bằng tay à? Nếu vậy thì chép file mới về thôi. Hồi trước cái file dùng để encode/decode transaction nằm trong thư mục `lib/transaction`, nhưng giờ nó nằm trong thưc mục `tx`. Chỉ là đổi tên thư mục thôi.

**Comment by vannghia17** [comment]
````js
let { encode, decode, verify, sign, hash } = require('../lib/tx');

let tx = {
    version: 1,
    sequence: 1,
    nemo: Buffer.alloc(0),
    operation: 'create_account',
    params: {
        address: 'GDMBJ447Y5XLBI2AHPR42NBCM46TIZQPHPPNCJJP25MJ3X6TLXO5KKSX'
    }
}

sign(tx, 'SDTCH4MUYJPHRHWMGGWXFO6PZF........');
````
Em đã import `lib/tx` nhưng khi sign vẫn bị lỗi "value must be a Buffer instance". Em coi source thì thầy đã chuyển từ  address: base32.decode(tx.params.address) thành address: Buffer.from(base32.decode(tx.params.address)). Bây giờ em phải truyền address vào theo kiểu nào ạ :( 

[
![screenshot_20181216_165252](https://user-images.githubusercontent.com/38467709/50052219-86621900-0153-11e9-91b5-601eeaddd0cc.png)
](url)
