### ISSUE TITLE
Wrong Block.Header.

### ISSUE THREAD

**Issue by progamerxh** [nguyenkha/forest.network#9]
app_1         | Begin block 3404 hash CD7364E41658A3DA5BE71057187191C882ED021AB20FB7377F1B87CDF5107369
app_1         | End block
app_1         | Commit block with app hash 5c2ac6c2062e29a6025b819d08d52422230232acb13a1ff01400b7d16200f019
app_1         | Begin block 3405 hash 425156CF53881242A796115BFCE01458AF91E9FE6E3993C9B343CBDC13726977
app_1         | Deliver tx
app_1         | End block
app_1         | Commit block with app hash 5c2ac6c2062e29a6025b819d08d52422230232acb13a1ff01400b7d16200f019
tendermint_1  | ERROR: Failed to create node: Error during handshake: Error on replay: Wrong Block.Header.AppHash.  Expected 5C2AC6C2062E29A6025B819D08D52422230232ACB13A1FF01400B7D16200F019, got 5890975F9AD63E26EB0AB605781A87C8C8BA3D318681AA6132C0C0BFC37F2F0

**Comment by progamerxh** [comment]
Em pull code mới về, compose down xong up thì bị lỗi như vậy ạ.
Em up bài bị lỗi mà không sửa được @@

**Comment by nguyenkha** [comment]
`down` rồi xóa thư muc `tenermint/data` chạy lại

**Comment by nguyenkha** [comment]
Hôm nay thầy mới bổ sung operation post và ai đó đã thử post trước khi thầy thông báo mọi người upgrade node nên code cũ chạy đến đó bị lỗi, dù update code vẫn phải sync lại (trừ khi đã update code mới trước block (3405)[https://forest.network/blocks/3405].

**Comment by progamerxh** [comment]
em làm theo thầy rồi tới node đó lại bị tiếp thầy ơi

**Comment by progamerxh** [comment]
em xóa data rồi chạy lại vẫn bị lỗi ở block đó thầy ơi @@

**Comment by nguyenkha** [comment]
Telegram nào...

**Comment by nguyenkha** [comment]
Chạy `docker-compose build` hoặc `docker-compose up --build`
